# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4af195f6fef5132b4768f5ade61f6a24ca40f7cd01f744be89679c10eb2fbd91953656e931b68753fc73854b55bbf169eefaa747c71da13a4223a9d3548d47e7

test:
  secret_key_base: dfbace359797129df3d8862c222e351a01cfe424bcde79b0835f97cd7a129c5b080b50c1520e2e10993e85d11ccab832bb0a68dcb52ebdde99007428d361431f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
